### ISSUE TITLE
Fixing CUDA dependency constraints

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ptxcompiler-feedstock#2]
Currently the dependency constraints here are incorrect. This package needs to build with the latest CUDA version and then it will support any earlier versions of CUDA. So this is the opposite of how conda-forge is doing things with CUDA Enhanced Compatibility. This may require some more work in the feedstock to get this working correctly. Please see [this recipe]( https://github.com/rapidsai/ptxcompiler/blob/eed289a36a68e252dc7bd2888b947c801756eec7/conda/recipes/ptxcompiler/meta.yaml#L20-L33 ) for details

**Comment by jakirkham** [comment]
cc @ajschmidt8 @Ethyling @gmarkall @quasiben (for viz)

**Comment by jakirkham** [comment]
Just to be a bit clearer here, the current packages are effectively broken until this is addressed

cc @prashantkhoje

**Comment by prashantkhoje** [comment]
The conda-forge doesn't yet support cudatoolkit 11.5/11.6.
Please review #7.

**Comment by prashantkhoje** [comment]
Addressed in #7.
Thank you for the inputs and review, @jakirkham. May i close this?

**Comment by jakirkham** [comment]
Thanks for working on that.

Last task is to mark the prior packages as broken, which is being handled in PR ( https://github.com/conda-forge/admin-requests/pull/425 )
